<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.thingsboard</groupId>
        <version>4.0.1</version>
        <artifactId>images</artifactId>
    </parent>
    <groupId>org.thingsboard.images</groupId>
    <artifactId>tb-transport-images</artifactId>
    <packaging>pom</packaging>

    <name>tb-transport-images</name>
    <url>https://thingsboard.io</url>

    <properties>
        <main.dir>${basedir}/../..</main.dir>
    </properties>

    <modules>
        <module>tb-mqtt-transport-image</module>
        <module>tb-http-transport-image</module>
        <module>tb-coap-transport-image</module>
        <module>tb-lwm2m-transport-image</module>
        <module>tb-snmp-transport-image</module>
        <module>tb-tcp-transport-image</module>
        <module>tb-udp-transport-image</module>
    </modules>
</project>
